services:
  project_hud:
    image: project_hud:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/New_York
      GITHUB_TOKEN:
      GITHUB_REPOS:
      USERNAME_MAP:
    restart: "no"
    command: "true"
